language: python
python:
  - "2.7"
services:
  - rabbitmq
before_install:
  - virtualenv ./pyenv --distribute
  - source ./pyenv/bin/activate
install:
  # To install external filter binaries, we first need to install
  # RubyGems and Node/NPM. I'm not sure why, since it seems clear
  # that NVM and RVM are pre-installed (see below).
  - sudo apt-get install python-software-properties
  - pip install -r requirements.txt -e .
  - pip install psycopg2 coveralls
before_script:
  - psql -c 'create database spendb;' -U postgres
  - cp prod_settings.py settings.py
  - nosetests --version
script:
  - nosetests --with-coverage --cover-package=spendb
after_success:
  - coveralls
