language: python
python:
  - "2.7"
services:
  - rabbitmq
before_install:
  - virtualenv ./pyenv --distribute
  - source ./pyenv/bin/activate
install:
  # To install external filter binaries, we first need to install
  # RubyGems and Node/NPM. I'm not sure why, since it seems clear
  # that NVM and RVM are pre-installed (see below).
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get install nodejs rubygems
  # These are useful for debugging this mess.
  #- env
  #- gem env
  #- rvm info
  # Use non-http registry? https://github.com/n1k0/casperjs/issues/876
  # Without this, installing doesn't work.
  - sudo npm config set registry http://registry.npmjs.org/
  - pip install -r requirements.txt -e .
  - pip install psycopg2
before_script:
  - psql -c 'create database spendb;' -U postgres
  - cp settings.py_tmpl settings.py
  - nosetests --version
script:
  - nosetests
